import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import { useForm, SubmitHandler } from 'react-hook-form';

import { useRouter } from 'next/router';

import { Button } from '@/components';
import { auth } from '@/pages/api/auth';

import styles from '@/styles/Auth.module.scss';

import logo from '@/assets/logo.svg';

type Inputs = {
  email: string;
  password: string;
};

export default function Login() {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<Inputs>();
  const router = useRouter();

  const [errorServer, setErrorServer] = React.useState<any>(null);
  const [responseServer, setResponseServer] = React.useState<any>(null);

  const onSubmitLogin: SubmitHandler<Inputs> = (data) => {
    auth({ link: '/login', setErrorServer, data, setResponseServer });
  };

  React.useEffect(() => {
    if (responseServer !== null) {
      localStorage.setItem('token', JSON.stringify(responseServer));
      setTimeout(() => {
        router.push('/');
      }, 1500);
    }
    if (localStorage.getItem('token')) {
      router.push('/');
    }
  }, [responseServer, router]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.auth}>
        <div className="panel">
          <Image src={logo} alt="logo" />

          <h1>Логін</h1>

          <form onSubmit={handleSubmit(onSubmitLogin)}>
            <div className="input">
              <label>Емайл</label>
              <input
                {...register('email', { required: true })}
                placeholder="Введіть емайл"
                type="email"
              />
              {errors.email && <span>Введіть емайл</span>}
              {errorServer && <span>{errorServer.user}</span>}
            </div>
            <div className="input">
              <label>Пароль</label>
              <input
                {...register('password', { required: true })}
                placeholder="Введіть пароль"
                type="password"
              />
              {errors.password && <span>Введіть пароль</span>}
              {errorServer && <span>{errorServer.password}</span>}
            </div>
            <div className={styles.link}>
              <Link href="/register">У вас немає акаунт</Link>
            </div>
            <Button type="submit" className="button">
              Логін
            </Button>
          </form>
        </div>
      </main>
    </>
  );
}
