import React from 'react';
import Head from 'next/head';

import { CreateItem, Loader, Provider, Sidebar } from '@/components';
import { UserProps } from '@/components/types';

import styles from '@/styles/page/Documets.module.scss';

import resume from '@/assets/icon/resume.svg';
import document from '@/assets/icon/document.svg';
import { useRouter } from 'next/router';

export default function Documets() {
  const router = useRouter();

  const [user, setUser] = React.useState<UserProps | null>(null);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Provider user={user} setUser={setUser}>
        <main className="main">
          <Sidebar user={user} />

          <section className="section">
            {user ? (
              <div className="container">
                <h1 className="title">Створити документ</h1>
                <div className={styles.content}>
                  <CreateItem
                    icon={resume}
                    name="Створити резюме"
                    link={`${router.pathname}/create-resume/1`}
                  />
                  <CreateItem
                    icon={document}
                    name="Створити ваканцію"
                    link={`${router.pathname}/create-vacancy/1`}
                  />
                </div>
              </div>
            ) : (
              <Loader />
            )}
          </section>
        </main>
      </Provider>
    </>
  );
}
