import React from 'react';
import Head from 'next/head';

import { Loader, Provider, Sidebar } from '@/components';

import { UserProps } from '@/components/types';

import styles from '@/styles/page/Info.module.scss';

export default function Info() {
  const [user, setUser] = React.useState<UserProps | null>(null);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Provider user={user} setUser={setUser}>
        <main className="main">
          <Sidebar user={user} />

          <section className="section info">
            {user ? (
              <div className="container">
                <div className={styles.content}>
                  <h1 className="title">Поради по пошуку роботи</h1>

                  <p className={styles.subhed}>
                    Ось декілька кроків, які ви можете виконати, щоб знайти роботу junior
                    програміста:
                  </p>
                  <ul>
                    <li>
                      Знайти потрібні технології: Вивчайте технології, які використовуються в
                      індустрії, і зосередьтеся на тих, які є популярними та затребуваними. Це
                      допоможе вам знайти роботу, де ви зможете використовувати свої навички.
                    </li>
                    <li>
                      Розширте свої знання: Вивчайте нові технології та мови програмування.
                      Більшість роботодавців бажають бачити, що ви можете працювати з різними
                      технологіями та мовами програмування.
                    </li>
                    <li>
                      Створіть профіль на сайтах для пошуку роботи: Наприклад, LinkedIn, Glassdoor,
                      Indeed, та Monster. Заповніть свій профіль повністю та додайте свої проекти та
                      навички. Більшість роботодавців шукають кандидатів саме на таких сайтах.
                    </li>
                    <li>
                      Подивіться на стажування та навчання: Багато компаній пропонують стажування
                      для junior програмістів, які навчаються на практиці. Це може бути відмінною
                      можливістю для вас навчитися новим технологіям та попрацювати над проектами.
                    </li>
                    <li>
                      Підтримуйте зв'язки з колегами та викладачами: Розширюйте свою мережу
                      знайомств, дізнайтеся про нові можливості та отримайте поради від своїх колег
                      та викладачів.
                    </li>
                    <li>
                      Підготуйтеся до співбесід: Для співбесіди підготуйтеся та вивчайте базові а
                    </li>
                  </ul>
                </div>
              </div>
            ) : (
              <Loader />
            )}
          </section>
        </main>
      </Provider>
    </>
  );
}
