import React from 'react';
import Head from 'next/head';

import { useRouter } from 'next/router';

import styles from '@/styles/Home.module.scss';

export default function Home() {
  const router = useRouter();

  React.useEffect(() => {
    if (!localStorage.getItem('token')) {
      router.push('/welcome');
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>Hello world!</main>
    </>
  );
}
