import React from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';

import { Button } from '@/components';

import styles from '@/styles/Welcome.module.scss';

export default function Welcome() {
  const router = useRouter();

  React.useEffect(() => {
    if (localStorage.getItem('token')) {
      router.push('/');
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.welcome}>
        <div className="panel">
          <h1>Вітаю у Junior Helpas</h1>
          <p>Ми компанія яка займається пошуком і створенням резюме для Junoir програмістів</p>
          <Button type="button" className="button" click={() => router.push('/register')}>
            Почати
          </Button>
        </div>
      </main>
    </>
  );
}
