import React from 'react';
import Head from 'next/head';

import { Loader, Provider, Sidebar } from '@/components';
import { UserProps } from '@/components/types';

import styles from '@/styles/page/CreateVacancy.module.scss';

export default function CreateVacancy() {
  const [user, setUser] = React.useState<UserProps | null>(null);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Provider user={user} setUser={setUser}>
        <main className="main">
          <Sidebar user={user} />

          <section className="section">
            {user ? (
              <div className="container">
                <h2 className="subtitle">Створити ваканцію</h2>
              </div>
            ) : (
              <Loader />
            )}
          </section>
        </main>
      </Provider>
    </>
  );
}
